version: '3.8'

services:
  fastapi:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app:app --host 0.0.0.0'
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
